# Generated by Django 6.0.2 on 2026-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(default='alkdjfhv@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
